# Generated by Django 4.2.9 on 2024-02-05 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('department_name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['department_name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=100)),
                ('student_name', models.CharField(max_length=100)),
                ('student_age', models.IntegerField(default=18)),
                ('student_email', models.EmailField(max_length=254, unique=True)),
                ('cgpa', models.FloatField(default=0.0)),
                ('address', models.TextField()),
                ('date_of_joining', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='core.department')),
            ],
            options={
                'ordering': ['student_id'],
            },
        ),
    ]
